version: '3.8'

services:
  db:
    image: postgres:15.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5435:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-redvike
    environment:
      - PORT=${PORT}
    depends_on:
      - db
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
